# Generated by Django 5.1.6 on 2025-03-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedphoto',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='uploadedphoto',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='uploadedphoto',
            name='submitted_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
