# Generated by Django 5.1.4 on 2024-12-17 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsprofileinfo',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctorsprofileinfo',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorsprofileinfo',
            name='clinic_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorsprofileinfo',
            name='doc_first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorsprofileinfo',
            name='doc_last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorsprofileinfo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/'),
        ),
        migrations.AlterField(
            model_name='doctorsprofileinfo',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorsprofileinfo',
            name='specialty',
            field=models.CharField(max_length=100),
        ),
    ]
