# Generated by Django 5.1.4 on 2024-12-28 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0002_doctoravailability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'verbose_name': 'Doctor Availability'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='availability',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='available_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customize.doctoravailability'),
        ),
    ]
