# Generated by Django 5.1.3 on 2024-11-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_doctorsprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsprofileinfo',
            name='phone',
            field=models.IntegerField(max_length=15),
        ),
    ]
