# Generated by Django 5.1.4 on 2025-01-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0002_alter_doctoravailability_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_appointments',
            name='available_booking',
        ),
    ]
