# Generated by Django 5.1.6 on 2025-03-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0002_remove_uploadedphoto_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedphoto',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
