# Generated by Django 5.1.4 on 2025-01-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0003_remove_booking_appointments_available_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedappointment',
            name='booked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookedappointment',
            name='appoinmnet_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bookedappointment',
            name='appoinmnet_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
