# Generated by Django 5.1.4 on 2025-02-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0003_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsprofileinfo',
            name='available',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
