# Generated by Django 5.1.4 on 2024-12-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0003_alter_doctoravailability_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='available',
            new_name='availability',
        ),
    ]
