# Generated by Django 5.1.4 on 2024-12-17 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0003_alter_doctorsprofileinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsprofileinfo',
            name='phone',
            field=models.CharField(help_text='Enter a valid 11-digit phone number (numeric only).', max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must consist of exactly 11 digits and be numeric.', regex='^\\d{11}$')]),
        ),
    ]
