# Generated by Django 5.1.4 on 2025-01-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0004_bookedappointment_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedappointment',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
