# Generated by Django 5.1.3 on 2024-11-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_doctorsprofileinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsprofileinfo',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
