# Generated by Django 5.1.4 on 2024-12-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0004_profile_age_profile_chronic_disease_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='chronic_disease',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
