# Generated by Django 5.1.4 on 2024-12-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0004_rename_available_doctoravailability_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
