# Generated by Django 5.1.4 on 2025-02-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0004_doctorsprofileinfo_available'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='doctoravailability',
            constraint=models.UniqueConstraint(fields=('doctor', 'date', 'start_time', 'end_time'), name='unique_doctor_availability'),
        ),
    ]
