# Generated by Django 5.1.4 on 2025-02-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0005_doctoravailability_unique_doctor_availability'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='doctoravailability',
            name='unique_doctor_availability',
        ),
        migrations.AddConstraint(
            model_name='doctoravailability',
            constraint=models.UniqueConstraint(fields=('doctor', 'date'), name='unique_doctor_availability'),
        ),
    ]
