# Generated by Django 5.1.4 on 2024-12-31 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0005_delete_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Booking Appointment'},
        ),
        migrations.AlterModelOptions(
            name='uploadedphoto',
            options={'verbose_name': 'Uploaded Photo'},
        ),
        migrations.AlterModelOptions(
            name='userlogin',
            options={'verbose_name': 'User Login'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='availability',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customize.doctorsprofileinfo'),
        ),
        migrations.AlterField(
            model_name='doctorsprofileinfo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='doc-imgs/'),
        ),
        migrations.DeleteModel(
            name='ActivityFeed',
        ),
    ]
