# Generated by Django 5.1.3 on 2024-11-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_doctorsprofileinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsprofileinfo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='doctors-images/'),
        ),
    ]
