# Generated by Django 5.1.4 on 2025-02-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0006_remove_doctoravailability_unique_doctor_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cancer_precentage',
            new_name='cancer_percentage',
        ),
    ]
