# Generated by Django 5.1.4 on 2025-02-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0007_rename_cancer_precentage_user_cancer_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cancer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, null=True),
        ),
    ]
