# Generated by Django 5.1.4 on 2025-01-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0007_rename_available_bookedappointment_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedappointment',
            name='booked',
        ),
        migrations.AddField(
            model_name='bookedappointment',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
