# Generated by Django 5.1.4 on 2025-01-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0008_remove_bookedappointment_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bookedappointment',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Already Booked'),
        ),
    ]
