# Generated by Django 5.1.4 on 2025-02-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0009_alter_user_cancer_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cancer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
