# Generated by Django 5.1.4 on 2025-01-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0010_alter_previoushistory_reciever'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
