# Generated by Django 5.1.4 on 2025-01-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0010_remove_booking_appointments_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedappointment',
            options={'verbose_name': 'Booked Appointment'},
        ),
        migrations.AlterModelOptions(
            name='booking_appointments',
            options={'verbose_name': 'Book an Appointment'},
        ),
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'verbose_name': 'Doctors Availabilitie'},
        ),
    ]
