# Generated by Django 5.1.4 on 2025-01-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0011_delete_userlogin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='PatientsProfile',
        ),
        migrations.AlterModelOptions(
            name='patientsprofile',
            options={'verbose_name': 'Patients Profile'},
        ),
    ]
