# Generated by Django 5.1.4 on 2025-01-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0011_alter_bookedappointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_appointments',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
