# Generated by Django 5.1.4 on 2025-01-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0012_booking_appointments_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking_appointments',
            options={'verbose_name': 'Book an appointment'},
        ),
    ]
