# Generated by Django 5.1.4 on 2025-01-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0012_rename_profile_patientsprofile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientsProfile',
            new_name='Profile',
        ),
    ]
