# Generated by Django 5.1.3 on 2024-12-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_appointment_date_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
