# Generated by Django 5.1.4 on 2025-01-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0014_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='availability',
        ),
    ]
