# Generated by Django 5.1.3 on 2024-12-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='choronic_disease',
            field=models.TextField(blank=True, default=None),
        ),
    ]
