# Generated by Django 5.1.4 on 2025-01-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0014_alter_bookedappointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'verbose_name': 'Doctors Availabilitie'},
        ),
        migrations.DeleteModel(
            name='BookedAppointment',
        ),
    ]
