# Generated by Django 5.1.4 on 2025-01-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0015_remove_doctoravailability_availability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Booking_Appointments',
        ),
        migrations.AlterModelOptions(
            name='booking_appointments',
            options={'verbose_name': 'Book An Appointment'},
        ),
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'verbose_name': 'Doctors Appointment'},
        ),
    ]
