# Generated by Django 5.1.4 on 2025-01-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0016_remove_booking_appointments_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_appointments',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
