# Generated by Django 5.1.4 on 2025-01-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0017_alter_booking_appointments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_appointments',
            name='time',
            field=models.TimeField(),
        ),
    ]
