# Generated by Django 5.1.4 on 2025-01-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0018_alter_booking_appointments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedphoto',
            name='photo',
            field=models.ImageField(default=None, upload_to='uploaded_photos/'),
        ),
    ]
