# Generated by Django 5.1.3 on 2024-12-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_doctorname_doctorsprofileinfo_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='first_name',
        ),
    ]
