# Generated by Django 5.1.4 on 2025-01-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0019_alter_uploadedphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previoushistory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
