# Generated by Django 5.1.3 on 2024-12-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_username_userprofile_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='user',
        ),
    ]
