# Generated by Django 5.1.4 on 2025-01-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0020_alter_previoushistory_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previoushistory',
            name='message',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='previoushistory',
            name='timestamp',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
