# Generated by Django 5.1.3 on 2024-12-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_first_name_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorsprofileinfo',
            old_name='user',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='patient',
        ),
    ]
