# Generated by Django 5.1.3 on 2024-12-06 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_rename_user_doctorsprofileinfo_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
