# Generated by Django 5.1.4 on 2025-01-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0022_alter_previoushistory_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previoushistory',
            name='timestamp',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
