# Generated by Django 5.1.3 on 2024-12-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_activityfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfeed',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
